// <auto-generated>
//     This code was generated by a tool on 2020-03-13-10:43:14
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using static System.Runtime.Intrinsics.X86.Avx;
using static System.Runtime.Intrinsics.X86.Avx2;

namespace VxSortResearch.Unstable.SmallSort
{
    static unsafe partial class GenericBitonicSort<T>
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort02VGeneric(ref Vector256<T> d01, ref Vector256<T> d02)
        {
            Vector256<T> tmp;

            BitonicSort01VGeneric(ref d01);
            BitonicSort01VGeneric(ref d02);

            tmp = Reverse(d02);
            d02 = MaxV(d01, tmp);
            d01 = MinV(d01, tmp);

            BitonicSort01VMergeGeneric(ref d01);
            BitonicSort01VMergeGeneric(ref d02);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort02VMergeGeneric(ref Vector256<T> d01, ref Vector256<T> d02)
        {
            Vector256<T> tmp;

            tmp = d01;
            d01 = MinV(d02, d01);
            d02 = MaxV(d02, tmp);

            BitonicSort01VMergeGeneric(ref d01);
            BitonicSort01VMergeGeneric(ref d02);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort03VGeneric(ref Vector256<T> d01, ref Vector256<T> d02, ref Vector256<T> d03)
        {
            Vector256<T> tmp;

            BitonicSort02VGeneric(ref d01, ref d02);
            BitonicSort01VGeneric(ref d03);

            tmp = Reverse(d03);
            d03 = MaxV(d02, tmp);
            d02 = MinV(d02, tmp);

            BitonicSort02VMergeGeneric(ref d01, ref d02);
            BitonicSort01VMergeGeneric(ref d03);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort03VMergeGeneric(ref Vector256<T> d01, ref Vector256<T> d02, ref Vector256<T> d03)
        {
            Vector256<T> tmp;

            tmp = d01;
            d01 = MinV(d03, d01);
            d03 = MaxV(d03, tmp);

            BitonicSort02VMergeGeneric(ref d01, ref d02);
            BitonicSort01VMergeGeneric(ref d03);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort04VGeneric(ref Vector256<T> d01, ref Vector256<T> d02, ref Vector256<T> d03, ref Vector256<T> d04)
        {
            Vector256<T> tmp;

            BitonicSort02VGeneric(ref d01, ref d02);
            BitonicSort02VGeneric(ref d03, ref d04);

            tmp = Reverse(d03);
            d03 = MaxV(d02, tmp);
            d02 = MinV(d02, tmp);

            tmp = Reverse(d04);
            d04 = MaxV(d01, tmp);
            d01 = MinV(d01, tmp);

            BitonicSort02VMergeGeneric(ref d01, ref d02);
            BitonicSort02VMergeGeneric(ref d03, ref d04);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort04VMergeGeneric(ref Vector256<T> d01, ref Vector256<T> d02, ref Vector256<T> d03, ref Vector256<T> d04)
        {
            Vector256<T> tmp;

            tmp = d01;
            d01 = MinV(d03, d01);
            d03 = MaxV(d03, tmp);

            tmp = d02;
            d02 = MinV(d04, d02);
            d04 = MaxV(d04, tmp);

            BitonicSort02VMergeGeneric(ref d01, ref d02);
            BitonicSort02VMergeGeneric(ref d03, ref d04);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort05VGeneric(ref Vector256<T> d01, ref Vector256<T> d02, ref Vector256<T> d03, ref Vector256<T> d04, ref Vector256<T> d05)
        {
            Vector256<T> tmp;

            BitonicSort04VGeneric(ref d01, ref d02, ref d03, ref d04);
            BitonicSort01VGeneric(ref d05);

            tmp = Reverse(d05);
            d05 = MaxV(d04, tmp);
            d04 = MinV(d04, tmp);

            BitonicSort04VMergeGeneric(ref d01, ref d02, ref d03, ref d04);
            BitonicSort01VMergeGeneric(ref d05);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort05VMergeGeneric(ref Vector256<T> d01, ref Vector256<T> d02, ref Vector256<T> d03, ref Vector256<T> d04, ref Vector256<T> d05)
        {
            Vector256<T> tmp;

            tmp = d01;
            d01 = MinV(d05, d01);
            d05 = MaxV(d05, tmp);

            BitonicSort04VMergeGeneric(ref d01, ref d02, ref d03, ref d04);
            BitonicSort01VMergeGeneric(ref d05);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort06VGeneric(ref Vector256<T> d01, ref Vector256<T> d02, ref Vector256<T> d03, ref Vector256<T> d04, ref Vector256<T> d05, ref Vector256<T> d06)
        {
            Vector256<T> tmp;

            BitonicSort04VGeneric(ref d01, ref d02, ref d03, ref d04);
            BitonicSort02VGeneric(ref d05, ref d06);

            tmp = Reverse(d05);
            d05 = MaxV(d04, tmp);
            d04 = MinV(d04, tmp);

            tmp = Reverse(d06);
            d06 = MaxV(d03, tmp);
            d03 = MinV(d03, tmp);

            BitonicSort04VMergeGeneric(ref d01, ref d02, ref d03, ref d04);
            BitonicSort02VMergeGeneric(ref d05, ref d06);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort06VMergeGeneric(ref Vector256<T> d01, ref Vector256<T> d02, ref Vector256<T> d03, ref Vector256<T> d04, ref Vector256<T> d05, ref Vector256<T> d06)
        {
            Vector256<T> tmp;

            tmp = d01;
            d01 = MinV(d05, d01);
            d05 = MaxV(d05, tmp);

            tmp = d02;
            d02 = MinV(d06, d02);
            d06 = MaxV(d06, tmp);

            BitonicSort04VMergeGeneric(ref d01, ref d02, ref d03, ref d04);
            BitonicSort02VMergeGeneric(ref d05, ref d06);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort07VGeneric(ref Vector256<T> d01, ref Vector256<T> d02, ref Vector256<T> d03, ref Vector256<T> d04, ref Vector256<T> d05, ref Vector256<T> d06, ref Vector256<T> d07)
        {
            Vector256<T> tmp;

            BitonicSort04VGeneric(ref d01, ref d02, ref d03, ref d04);
            BitonicSort03VGeneric(ref d05, ref d06, ref d07);

            tmp = Reverse(d05);
            d05 = MaxV(d04, tmp);
            d04 = MinV(d04, tmp);

            tmp = Reverse(d06);
            d06 = MaxV(d03, tmp);
            d03 = MinV(d03, tmp);

            tmp = Reverse(d07);
            d07 = MaxV(d02, tmp);
            d02 = MinV(d02, tmp);

            BitonicSort04VMergeGeneric(ref d01, ref d02, ref d03, ref d04);
            BitonicSort03VMergeGeneric(ref d05, ref d06, ref d07);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort07VMergeGeneric(ref Vector256<T> d01, ref Vector256<T> d02, ref Vector256<T> d03, ref Vector256<T> d04, ref Vector256<T> d05, ref Vector256<T> d06, ref Vector256<T> d07)
        {
            Vector256<T> tmp;

            tmp = d01;
            d01 = MinV(d05, d01);
            d05 = MaxV(d05, tmp);

            tmp = d02;
            d02 = MinV(d06, d02);
            d06 = MaxV(d06, tmp);

            tmp = d03;
            d03 = MinV(d07, d03);
            d07 = MaxV(d07, tmp);

            BitonicSort04VMergeGeneric(ref d01, ref d02, ref d03, ref d04);
            BitonicSort03VMergeGeneric(ref d05, ref d06, ref d07);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort08VGeneric(ref Vector256<T> d01, ref Vector256<T> d02, ref Vector256<T> d03, ref Vector256<T> d04, ref Vector256<T> d05, ref Vector256<T> d06, ref Vector256<T> d07, ref Vector256<T> d08)
        {
            Vector256<T> tmp;

            BitonicSort04VGeneric(ref d01, ref d02, ref d03, ref d04);
            BitonicSort04VGeneric(ref d05, ref d06, ref d07, ref d08);

            tmp = Reverse(d05);
            d05 = MaxV(d04, tmp);
            d04 = MinV(d04, tmp);

            tmp = Reverse(d06);
            d06 = MaxV(d03, tmp);
            d03 = MinV(d03, tmp);

            tmp = Reverse(d07);
            d07 = MaxV(d02, tmp);
            d02 = MinV(d02, tmp);

            tmp = Reverse(d08);
            d08 = MaxV(d01, tmp);
            d01 = MinV(d01, tmp);

            BitonicSort04VMergeGeneric(ref d01, ref d02, ref d03, ref d04);
            BitonicSort04VMergeGeneric(ref d05, ref d06, ref d07, ref d08);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort08VMergeGeneric(ref Vector256<T> d01, ref Vector256<T> d02, ref Vector256<T> d03, ref Vector256<T> d04, ref Vector256<T> d05, ref Vector256<T> d06, ref Vector256<T> d07, ref Vector256<T> d08)
        {
            Vector256<T> tmp;

            tmp = d01;
            d01 = MinV(d05, d01);
            d05 = MaxV(d05, tmp);

            tmp = d02;
            d02 = MinV(d06, d02);
            d06 = MaxV(d06, tmp);

            tmp = d03;
            d03 = MinV(d07, d03);
            d07 = MaxV(d07, tmp);

            tmp = d04;
            d04 = MinV(d08, d04);
            d08 = MaxV(d08, tmp);

            BitonicSort04VMergeGeneric(ref d01, ref d02, ref d03, ref d04);
            BitonicSort04VMergeGeneric(ref d05, ref d06, ref d07, ref d08);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort09VGeneric(ref Vector256<T> d01, ref Vector256<T> d02, ref Vector256<T> d03, ref Vector256<T> d04, ref Vector256<T> d05, ref Vector256<T> d06, ref Vector256<T> d07, ref Vector256<T> d08, ref Vector256<T> d09)
        {
            Vector256<T> tmp;

            BitonicSort08VGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08);
            BitonicSort01VGeneric(ref d09);

            tmp = Reverse(d09);
            d09 = MaxV(d08, tmp);
            d08 = MinV(d08, tmp);

            BitonicSort08VMergeGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08);
            BitonicSort01VMergeGeneric(ref d09);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort10VGeneric(ref Vector256<T> d01, ref Vector256<T> d02, ref Vector256<T> d03, ref Vector256<T> d04, ref Vector256<T> d05, ref Vector256<T> d06, ref Vector256<T> d07, ref Vector256<T> d08, ref Vector256<T> d09, ref Vector256<T> d10)
        {
            Vector256<T> tmp;

            BitonicSort08VGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08);
            BitonicSort02VGeneric(ref d09, ref d10);

            tmp = Reverse(d09);
            d09 = MaxV(d08, tmp);
            d08 = MinV(d08, tmp);

            tmp = Reverse(d10);
            d10 = MaxV(d07, tmp);
            d07 = MinV(d07, tmp);

            BitonicSort08VMergeGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08);
            BitonicSort02VMergeGeneric(ref d09, ref d10);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort11VGeneric(ref Vector256<T> d01, ref Vector256<T> d02, ref Vector256<T> d03, ref Vector256<T> d04, ref Vector256<T> d05, ref Vector256<T> d06, ref Vector256<T> d07, ref Vector256<T> d08, ref Vector256<T> d09, ref Vector256<T> d10, ref Vector256<T> d11)
        {
            Vector256<T> tmp;

            BitonicSort08VGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08);
            BitonicSort03VGeneric(ref d09, ref d10, ref d11);

            tmp = Reverse(d09);
            d09 = MaxV(d08, tmp);
            d08 = MinV(d08, tmp);

            tmp = Reverse(d10);
            d10 = MaxV(d07, tmp);
            d07 = MinV(d07, tmp);

            tmp = Reverse(d11);
            d11 = MaxV(d06, tmp);
            d06 = MinV(d06, tmp);

            BitonicSort08VMergeGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08);
            BitonicSort03VMergeGeneric(ref d09, ref d10, ref d11);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort12VGeneric(ref Vector256<T> d01, ref Vector256<T> d02, ref Vector256<T> d03, ref Vector256<T> d04, ref Vector256<T> d05, ref Vector256<T> d06, ref Vector256<T> d07, ref Vector256<T> d08, ref Vector256<T> d09, ref Vector256<T> d10, ref Vector256<T> d11, ref Vector256<T> d12)
        {
            Vector256<T> tmp;

            BitonicSort08VGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08);
            BitonicSort04VGeneric(ref d09, ref d10, ref d11, ref d12);

            tmp = Reverse(d09);
            d09 = MaxV(d08, tmp);
            d08 = MinV(d08, tmp);

            tmp = Reverse(d10);
            d10 = MaxV(d07, tmp);
            d07 = MinV(d07, tmp);

            tmp = Reverse(d11);
            d11 = MaxV(d06, tmp);
            d06 = MinV(d06, tmp);

            tmp = Reverse(d12);
            d12 = MaxV(d05, tmp);
            d05 = MinV(d05, tmp);

            BitonicSort08VMergeGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08);
            BitonicSort04VMergeGeneric(ref d09, ref d10, ref d11, ref d12);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort13VGeneric(ref Vector256<T> d01, ref Vector256<T> d02, ref Vector256<T> d03, ref Vector256<T> d04, ref Vector256<T> d05, ref Vector256<T> d06, ref Vector256<T> d07, ref Vector256<T> d08, ref Vector256<T> d09, ref Vector256<T> d10, ref Vector256<T> d11, ref Vector256<T> d12, ref Vector256<T> d13)
        {
            Vector256<T> tmp;

            BitonicSort08VGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08);
            BitonicSort05VGeneric(ref d09, ref d10, ref d11, ref d12, ref d13);

            tmp = Reverse(d09);
            d09 = MaxV(d08, tmp);
            d08 = MinV(d08, tmp);

            tmp = Reverse(d10);
            d10 = MaxV(d07, tmp);
            d07 = MinV(d07, tmp);

            tmp = Reverse(d11);
            d11 = MaxV(d06, tmp);
            d06 = MinV(d06, tmp);

            tmp = Reverse(d12);
            d12 = MaxV(d05, tmp);
            d05 = MinV(d05, tmp);

            tmp = Reverse(d13);
            d13 = MaxV(d04, tmp);
            d04 = MinV(d04, tmp);

            BitonicSort08VMergeGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08);
            BitonicSort05VMergeGeneric(ref d09, ref d10, ref d11, ref d12, ref d13);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort14VGeneric(ref Vector256<T> d01, ref Vector256<T> d02, ref Vector256<T> d03, ref Vector256<T> d04, ref Vector256<T> d05, ref Vector256<T> d06, ref Vector256<T> d07, ref Vector256<T> d08, ref Vector256<T> d09, ref Vector256<T> d10, ref Vector256<T> d11, ref Vector256<T> d12, ref Vector256<T> d13, ref Vector256<T> d14)
        {
            Vector256<T> tmp;

            BitonicSort08VGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08);
            BitonicSort06VGeneric(ref d09, ref d10, ref d11, ref d12, ref d13, ref d14);

            tmp = Reverse(d09);
            d09 = MaxV(d08, tmp);
            d08 = MinV(d08, tmp);

            tmp = Reverse(d10);
            d10 = MaxV(d07, tmp);
            d07 = MinV(d07, tmp);

            tmp = Reverse(d11);
            d11 = MaxV(d06, tmp);
            d06 = MinV(d06, tmp);

            tmp = Reverse(d12);
            d12 = MaxV(d05, tmp);
            d05 = MinV(d05, tmp);

            tmp = Reverse(d13);
            d13 = MaxV(d04, tmp);
            d04 = MinV(d04, tmp);

            tmp = Reverse(d14);
            d14 = MaxV(d03, tmp);
            d03 = MinV(d03, tmp);

            BitonicSort08VMergeGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08);
            BitonicSort06VMergeGeneric(ref d09, ref d10, ref d11, ref d12, ref d13, ref d14);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort15VGeneric(ref Vector256<T> d01, ref Vector256<T> d02, ref Vector256<T> d03, ref Vector256<T> d04, ref Vector256<T> d05, ref Vector256<T> d06, ref Vector256<T> d07, ref Vector256<T> d08, ref Vector256<T> d09, ref Vector256<T> d10, ref Vector256<T> d11, ref Vector256<T> d12, ref Vector256<T> d13, ref Vector256<T> d14, ref Vector256<T> d15)
        {
            Vector256<T> tmp;

            BitonicSort08VGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08);
            BitonicSort07VGeneric(ref d09, ref d10, ref d11, ref d12, ref d13, ref d14, ref d15);

            tmp = Reverse(d09);
            d09 = MaxV(d08, tmp);
            d08 = MinV(d08, tmp);

            tmp = Reverse(d10);
            d10 = MaxV(d07, tmp);
            d07 = MinV(d07, tmp);

            tmp = Reverse(d11);
            d11 = MaxV(d06, tmp);
            d06 = MinV(d06, tmp);

            tmp = Reverse(d12);
            d12 = MaxV(d05, tmp);
            d05 = MinV(d05, tmp);

            tmp = Reverse(d13);
            d13 = MaxV(d04, tmp);
            d04 = MinV(d04, tmp);

            tmp = Reverse(d14);
            d14 = MaxV(d03, tmp);
            d03 = MinV(d03, tmp);

            tmp = Reverse(d15);
            d15 = MaxV(d02, tmp);
            d02 = MinV(d02, tmp);

            BitonicSort08VMergeGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08);
            BitonicSort07VMergeGeneric(ref d09, ref d10, ref d11, ref d12, ref d13, ref d14, ref d15);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort16VGeneric(ref Vector256<T> d01, ref Vector256<T> d02, ref Vector256<T> d03, ref Vector256<T> d04, ref Vector256<T> d05, ref Vector256<T> d06, ref Vector256<T> d07, ref Vector256<T> d08, ref Vector256<T> d09, ref Vector256<T> d10, ref Vector256<T> d11, ref Vector256<T> d12, ref Vector256<T> d13, ref Vector256<T> d14, ref Vector256<T> d15, ref Vector256<T> d16)
        {
            Vector256<T> tmp;

            BitonicSort08VGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08);
            BitonicSort08VGeneric(ref d09, ref d10, ref d11, ref d12, ref d13, ref d14, ref d15, ref d16);

            tmp = Reverse(d09);
            d09 = MaxV(d08, tmp);
            d08 = MinV(d08, tmp);

            tmp = Reverse(d10);
            d10 = MaxV(d07, tmp);
            d07 = MinV(d07, tmp);

            tmp = Reverse(d11);
            d11 = MaxV(d06, tmp);
            d06 = MinV(d06, tmp);

            tmp = Reverse(d12);
            d12 = MaxV(d05, tmp);
            d05 = MinV(d05, tmp);

            tmp = Reverse(d13);
            d13 = MaxV(d04, tmp);
            d04 = MinV(d04, tmp);

            tmp = Reverse(d14);
            d14 = MaxV(d03, tmp);
            d03 = MinV(d03, tmp);

            tmp = Reverse(d15);
            d15 = MaxV(d02, tmp);
            d02 = MinV(d02, tmp);

            tmp = Reverse(d16);
            d16 = MaxV(d01, tmp);
            d01 = MinV(d01, tmp);

            BitonicSort08VMergeGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08);
            BitonicSort08VMergeGeneric(ref d09, ref d10, ref d11, ref d12, ref d13, ref d14, ref d15, ref d16);
        }


        [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort01V(T* ptr)
        {
            var N = Vector256<T>.Count;

            var d01 = LoadDquVector256((byte *) ptr + 00*N*Unsafe.SizeOf<T>()).As<byte, T>();

            BitonicSort01VGeneric(ref d01);

            Store((byte *) ptr + 00*N*Unsafe.SizeOf<T>(), d01.AsByte());
        }
        [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort02V(T* ptr)
        {
            var N = Vector256<T>.Count;

            var d01 = LoadDquVector256((byte *) ptr + 00*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d02 = LoadDquVector256((byte *) ptr + 01*N*Unsafe.SizeOf<T>()).As<byte, T>();

            BitonicSort02VGeneric(ref d01, ref d02);

            Store((byte *) ptr + 00*N*Unsafe.SizeOf<T>(), d01.AsByte());
            Store((byte *) ptr + 01*N*Unsafe.SizeOf<T>(), d02.AsByte());
        }
        [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort03V(T* ptr)
        {
            var N = Vector256<T>.Count;

            var d01 = LoadDquVector256((byte *) ptr + 00*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d02 = LoadDquVector256((byte *) ptr + 01*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d03 = LoadDquVector256((byte *) ptr + 02*N*Unsafe.SizeOf<T>()).As<byte, T>();

            BitonicSort03VGeneric(ref d01, ref d02, ref d03);

            Store((byte *) ptr + 00*N*Unsafe.SizeOf<T>(), d01.AsByte());
            Store((byte *) ptr + 01*N*Unsafe.SizeOf<T>(), d02.AsByte());
            Store((byte *) ptr + 02*N*Unsafe.SizeOf<T>(), d03.AsByte());
        }
        [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort04V(T* ptr)
        {
            var N = Vector256<T>.Count;

            var d01 = LoadDquVector256((byte *) ptr + 00*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d02 = LoadDquVector256((byte *) ptr + 01*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d03 = LoadDquVector256((byte *) ptr + 02*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d04 = LoadDquVector256((byte *) ptr + 03*N*Unsafe.SizeOf<T>()).As<byte, T>();

            BitonicSort04VGeneric(ref d01, ref d02, ref d03, ref d04);

            Store((byte *) ptr + 00*N*Unsafe.SizeOf<T>(), d01.AsByte());
            Store((byte *) ptr + 01*N*Unsafe.SizeOf<T>(), d02.AsByte());
            Store((byte *) ptr + 02*N*Unsafe.SizeOf<T>(), d03.AsByte());
            Store((byte *) ptr + 03*N*Unsafe.SizeOf<T>(), d04.AsByte());
        }
        [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort05V(T* ptr)
        {
            var N = Vector256<T>.Count;

            var d01 = LoadDquVector256((byte *) ptr + 00*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d02 = LoadDquVector256((byte *) ptr + 01*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d03 = LoadDquVector256((byte *) ptr + 02*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d04 = LoadDquVector256((byte *) ptr + 03*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d05 = LoadDquVector256((byte *) ptr + 04*N*Unsafe.SizeOf<T>()).As<byte, T>();

            BitonicSort05VGeneric(ref d01, ref d02, ref d03, ref d04, ref d05);

            Store((byte *) ptr + 00*N*Unsafe.SizeOf<T>(), d01.AsByte());
            Store((byte *) ptr + 01*N*Unsafe.SizeOf<T>(), d02.AsByte());
            Store((byte *) ptr + 02*N*Unsafe.SizeOf<T>(), d03.AsByte());
            Store((byte *) ptr + 03*N*Unsafe.SizeOf<T>(), d04.AsByte());
            Store((byte *) ptr + 04*N*Unsafe.SizeOf<T>(), d05.AsByte());
        }
        [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort06V(T* ptr)
        {
            var N = Vector256<T>.Count;

            var d01 = LoadDquVector256((byte *) ptr + 00*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d02 = LoadDquVector256((byte *) ptr + 01*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d03 = LoadDquVector256((byte *) ptr + 02*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d04 = LoadDquVector256((byte *) ptr + 03*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d05 = LoadDquVector256((byte *) ptr + 04*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d06 = LoadDquVector256((byte *) ptr + 05*N*Unsafe.SizeOf<T>()).As<byte, T>();

            BitonicSort06VGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06);

            Store((byte *) ptr + 00*N*Unsafe.SizeOf<T>(), d01.AsByte());
            Store((byte *) ptr + 01*N*Unsafe.SizeOf<T>(), d02.AsByte());
            Store((byte *) ptr + 02*N*Unsafe.SizeOf<T>(), d03.AsByte());
            Store((byte *) ptr + 03*N*Unsafe.SizeOf<T>(), d04.AsByte());
            Store((byte *) ptr + 04*N*Unsafe.SizeOf<T>(), d05.AsByte());
            Store((byte *) ptr + 05*N*Unsafe.SizeOf<T>(), d06.AsByte());
        }
        [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort07V(T* ptr)
        {
            var N = Vector256<T>.Count;

            var d01 = LoadDquVector256((byte *) ptr + 00*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d02 = LoadDquVector256((byte *) ptr + 01*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d03 = LoadDquVector256((byte *) ptr + 02*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d04 = LoadDquVector256((byte *) ptr + 03*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d05 = LoadDquVector256((byte *) ptr + 04*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d06 = LoadDquVector256((byte *) ptr + 05*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d07 = LoadDquVector256((byte *) ptr + 06*N*Unsafe.SizeOf<T>()).As<byte, T>();

            BitonicSort07VGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07);

            Store((byte *) ptr + 00*N*Unsafe.SizeOf<T>(), d01.AsByte());
            Store((byte *) ptr + 01*N*Unsafe.SizeOf<T>(), d02.AsByte());
            Store((byte *) ptr + 02*N*Unsafe.SizeOf<T>(), d03.AsByte());
            Store((byte *) ptr + 03*N*Unsafe.SizeOf<T>(), d04.AsByte());
            Store((byte *) ptr + 04*N*Unsafe.SizeOf<T>(), d05.AsByte());
            Store((byte *) ptr + 05*N*Unsafe.SizeOf<T>(), d06.AsByte());
            Store((byte *) ptr + 06*N*Unsafe.SizeOf<T>(), d07.AsByte());
        }
        [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort08V(T* ptr)
        {
            var N = Vector256<T>.Count;

            var d01 = LoadDquVector256((byte *) ptr + 00*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d02 = LoadDquVector256((byte *) ptr + 01*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d03 = LoadDquVector256((byte *) ptr + 02*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d04 = LoadDquVector256((byte *) ptr + 03*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d05 = LoadDquVector256((byte *) ptr + 04*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d06 = LoadDquVector256((byte *) ptr + 05*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d07 = LoadDquVector256((byte *) ptr + 06*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d08 = LoadDquVector256((byte *) ptr + 07*N*Unsafe.SizeOf<T>()).As<byte, T>();

            BitonicSort08VGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08);

            Store((byte *) ptr + 00*N*Unsafe.SizeOf<T>(), d01.AsByte());
            Store((byte *) ptr + 01*N*Unsafe.SizeOf<T>(), d02.AsByte());
            Store((byte *) ptr + 02*N*Unsafe.SizeOf<T>(), d03.AsByte());
            Store((byte *) ptr + 03*N*Unsafe.SizeOf<T>(), d04.AsByte());
            Store((byte *) ptr + 04*N*Unsafe.SizeOf<T>(), d05.AsByte());
            Store((byte *) ptr + 05*N*Unsafe.SizeOf<T>(), d06.AsByte());
            Store((byte *) ptr + 06*N*Unsafe.SizeOf<T>(), d07.AsByte());
            Store((byte *) ptr + 07*N*Unsafe.SizeOf<T>(), d08.AsByte());
        }
        [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort09V(T* ptr)
        {
            var N = Vector256<T>.Count;

            var d01 = LoadDquVector256((byte *) ptr + 00*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d02 = LoadDquVector256((byte *) ptr + 01*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d03 = LoadDquVector256((byte *) ptr + 02*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d04 = LoadDquVector256((byte *) ptr + 03*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d05 = LoadDquVector256((byte *) ptr + 04*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d06 = LoadDquVector256((byte *) ptr + 05*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d07 = LoadDquVector256((byte *) ptr + 06*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d08 = LoadDquVector256((byte *) ptr + 07*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d09 = LoadDquVector256((byte *) ptr + 08*N*Unsafe.SizeOf<T>()).As<byte, T>();

            BitonicSort09VGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08, ref d09);

            Store((byte *) ptr + 00*N*Unsafe.SizeOf<T>(), d01.AsByte());
            Store((byte *) ptr + 01*N*Unsafe.SizeOf<T>(), d02.AsByte());
            Store((byte *) ptr + 02*N*Unsafe.SizeOf<T>(), d03.AsByte());
            Store((byte *) ptr + 03*N*Unsafe.SizeOf<T>(), d04.AsByte());
            Store((byte *) ptr + 04*N*Unsafe.SizeOf<T>(), d05.AsByte());
            Store((byte *) ptr + 05*N*Unsafe.SizeOf<T>(), d06.AsByte());
            Store((byte *) ptr + 06*N*Unsafe.SizeOf<T>(), d07.AsByte());
            Store((byte *) ptr + 07*N*Unsafe.SizeOf<T>(), d08.AsByte());
            Store((byte *) ptr + 08*N*Unsafe.SizeOf<T>(), d09.AsByte());
        }
        [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort10V(T* ptr)
        {
            var N = Vector256<T>.Count;

            var d01 = LoadDquVector256((byte *) ptr + 00*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d02 = LoadDquVector256((byte *) ptr + 01*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d03 = LoadDquVector256((byte *) ptr + 02*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d04 = LoadDquVector256((byte *) ptr + 03*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d05 = LoadDquVector256((byte *) ptr + 04*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d06 = LoadDquVector256((byte *) ptr + 05*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d07 = LoadDquVector256((byte *) ptr + 06*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d08 = LoadDquVector256((byte *) ptr + 07*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d09 = LoadDquVector256((byte *) ptr + 08*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d10 = LoadDquVector256((byte *) ptr + 09*N*Unsafe.SizeOf<T>()).As<byte, T>();

            BitonicSort10VGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08, ref d09, ref d10);

            Store((byte *) ptr + 00*N*Unsafe.SizeOf<T>(), d01.AsByte());
            Store((byte *) ptr + 01*N*Unsafe.SizeOf<T>(), d02.AsByte());
            Store((byte *) ptr + 02*N*Unsafe.SizeOf<T>(), d03.AsByte());
            Store((byte *) ptr + 03*N*Unsafe.SizeOf<T>(), d04.AsByte());
            Store((byte *) ptr + 04*N*Unsafe.SizeOf<T>(), d05.AsByte());
            Store((byte *) ptr + 05*N*Unsafe.SizeOf<T>(), d06.AsByte());
            Store((byte *) ptr + 06*N*Unsafe.SizeOf<T>(), d07.AsByte());
            Store((byte *) ptr + 07*N*Unsafe.SizeOf<T>(), d08.AsByte());
            Store((byte *) ptr + 08*N*Unsafe.SizeOf<T>(), d09.AsByte());
            Store((byte *) ptr + 09*N*Unsafe.SizeOf<T>(), d10.AsByte());
        }
        [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort11V(T* ptr)
        {
            var N = Vector256<T>.Count;

            var d01 = LoadDquVector256((byte *) ptr + 00*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d02 = LoadDquVector256((byte *) ptr + 01*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d03 = LoadDquVector256((byte *) ptr + 02*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d04 = LoadDquVector256((byte *) ptr + 03*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d05 = LoadDquVector256((byte *) ptr + 04*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d06 = LoadDquVector256((byte *) ptr + 05*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d07 = LoadDquVector256((byte *) ptr + 06*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d08 = LoadDquVector256((byte *) ptr + 07*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d09 = LoadDquVector256((byte *) ptr + 08*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d10 = LoadDquVector256((byte *) ptr + 09*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d11 = LoadDquVector256((byte *) ptr + 10*N*Unsafe.SizeOf<T>()).As<byte, T>();

            BitonicSort11VGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08, ref d09, ref d10, ref d11);

            Store((byte *) ptr + 00*N*Unsafe.SizeOf<T>(), d01.AsByte());
            Store((byte *) ptr + 01*N*Unsafe.SizeOf<T>(), d02.AsByte());
            Store((byte *) ptr + 02*N*Unsafe.SizeOf<T>(), d03.AsByte());
            Store((byte *) ptr + 03*N*Unsafe.SizeOf<T>(), d04.AsByte());
            Store((byte *) ptr + 04*N*Unsafe.SizeOf<T>(), d05.AsByte());
            Store((byte *) ptr + 05*N*Unsafe.SizeOf<T>(), d06.AsByte());
            Store((byte *) ptr + 06*N*Unsafe.SizeOf<T>(), d07.AsByte());
            Store((byte *) ptr + 07*N*Unsafe.SizeOf<T>(), d08.AsByte());
            Store((byte *) ptr + 08*N*Unsafe.SizeOf<T>(), d09.AsByte());
            Store((byte *) ptr + 09*N*Unsafe.SizeOf<T>(), d10.AsByte());
            Store((byte *) ptr + 10*N*Unsafe.SizeOf<T>(), d11.AsByte());
        }
        [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort12V(T* ptr)
        {
            var N = Vector256<T>.Count;

            var d01 = LoadDquVector256((byte *) ptr + 00*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d02 = LoadDquVector256((byte *) ptr + 01*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d03 = LoadDquVector256((byte *) ptr + 02*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d04 = LoadDquVector256((byte *) ptr + 03*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d05 = LoadDquVector256((byte *) ptr + 04*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d06 = LoadDquVector256((byte *) ptr + 05*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d07 = LoadDquVector256((byte *) ptr + 06*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d08 = LoadDquVector256((byte *) ptr + 07*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d09 = LoadDquVector256((byte *) ptr + 08*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d10 = LoadDquVector256((byte *) ptr + 09*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d11 = LoadDquVector256((byte *) ptr + 10*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d12 = LoadDquVector256((byte *) ptr + 11*N*Unsafe.SizeOf<T>()).As<byte, T>();

            BitonicSort12VGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08, ref d09, ref d10, ref d11, ref d12);

            Store((byte *) ptr + 00*N*Unsafe.SizeOf<T>(), d01.AsByte());
            Store((byte *) ptr + 01*N*Unsafe.SizeOf<T>(), d02.AsByte());
            Store((byte *) ptr + 02*N*Unsafe.SizeOf<T>(), d03.AsByte());
            Store((byte *) ptr + 03*N*Unsafe.SizeOf<T>(), d04.AsByte());
            Store((byte *) ptr + 04*N*Unsafe.SizeOf<T>(), d05.AsByte());
            Store((byte *) ptr + 05*N*Unsafe.SizeOf<T>(), d06.AsByte());
            Store((byte *) ptr + 06*N*Unsafe.SizeOf<T>(), d07.AsByte());
            Store((byte *) ptr + 07*N*Unsafe.SizeOf<T>(), d08.AsByte());
            Store((byte *) ptr + 08*N*Unsafe.SizeOf<T>(), d09.AsByte());
            Store((byte *) ptr + 09*N*Unsafe.SizeOf<T>(), d10.AsByte());
            Store((byte *) ptr + 10*N*Unsafe.SizeOf<T>(), d11.AsByte());
            Store((byte *) ptr + 11*N*Unsafe.SizeOf<T>(), d12.AsByte());
        }
        [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort13V(T* ptr)
        {
            var N = Vector256<T>.Count;

            var d01 = LoadDquVector256((byte *) ptr + 00*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d02 = LoadDquVector256((byte *) ptr + 01*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d03 = LoadDquVector256((byte *) ptr + 02*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d04 = LoadDquVector256((byte *) ptr + 03*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d05 = LoadDquVector256((byte *) ptr + 04*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d06 = LoadDquVector256((byte *) ptr + 05*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d07 = LoadDquVector256((byte *) ptr + 06*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d08 = LoadDquVector256((byte *) ptr + 07*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d09 = LoadDquVector256((byte *) ptr + 08*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d10 = LoadDquVector256((byte *) ptr + 09*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d11 = LoadDquVector256((byte *) ptr + 10*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d12 = LoadDquVector256((byte *) ptr + 11*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d13 = LoadDquVector256((byte *) ptr + 12*N*Unsafe.SizeOf<T>()).As<byte, T>();

            BitonicSort13VGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08, ref d09, ref d10, ref d11, ref d12, ref d13);

            Store((byte *) ptr + 00*N*Unsafe.SizeOf<T>(), d01.AsByte());
            Store((byte *) ptr + 01*N*Unsafe.SizeOf<T>(), d02.AsByte());
            Store((byte *) ptr + 02*N*Unsafe.SizeOf<T>(), d03.AsByte());
            Store((byte *) ptr + 03*N*Unsafe.SizeOf<T>(), d04.AsByte());
            Store((byte *) ptr + 04*N*Unsafe.SizeOf<T>(), d05.AsByte());
            Store((byte *) ptr + 05*N*Unsafe.SizeOf<T>(), d06.AsByte());
            Store((byte *) ptr + 06*N*Unsafe.SizeOf<T>(), d07.AsByte());
            Store((byte *) ptr + 07*N*Unsafe.SizeOf<T>(), d08.AsByte());
            Store((byte *) ptr + 08*N*Unsafe.SizeOf<T>(), d09.AsByte());
            Store((byte *) ptr + 09*N*Unsafe.SizeOf<T>(), d10.AsByte());
            Store((byte *) ptr + 10*N*Unsafe.SizeOf<T>(), d11.AsByte());
            Store((byte *) ptr + 11*N*Unsafe.SizeOf<T>(), d12.AsByte());
            Store((byte *) ptr + 12*N*Unsafe.SizeOf<T>(), d13.AsByte());
        }
        [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort14V(T* ptr)
        {
            var N = Vector256<T>.Count;

            var d01 = LoadDquVector256((byte *) ptr + 00*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d02 = LoadDquVector256((byte *) ptr + 01*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d03 = LoadDquVector256((byte *) ptr + 02*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d04 = LoadDquVector256((byte *) ptr + 03*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d05 = LoadDquVector256((byte *) ptr + 04*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d06 = LoadDquVector256((byte *) ptr + 05*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d07 = LoadDquVector256((byte *) ptr + 06*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d08 = LoadDquVector256((byte *) ptr + 07*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d09 = LoadDquVector256((byte *) ptr + 08*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d10 = LoadDquVector256((byte *) ptr + 09*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d11 = LoadDquVector256((byte *) ptr + 10*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d12 = LoadDquVector256((byte *) ptr + 11*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d13 = LoadDquVector256((byte *) ptr + 12*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d14 = LoadDquVector256((byte *) ptr + 13*N*Unsafe.SizeOf<T>()).As<byte, T>();

            BitonicSort14VGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08, ref d09, ref d10, ref d11, ref d12, ref d13, ref d14);

            Store((byte *) ptr + 00*N*Unsafe.SizeOf<T>(), d01.AsByte());
            Store((byte *) ptr + 01*N*Unsafe.SizeOf<T>(), d02.AsByte());
            Store((byte *) ptr + 02*N*Unsafe.SizeOf<T>(), d03.AsByte());
            Store((byte *) ptr + 03*N*Unsafe.SizeOf<T>(), d04.AsByte());
            Store((byte *) ptr + 04*N*Unsafe.SizeOf<T>(), d05.AsByte());
            Store((byte *) ptr + 05*N*Unsafe.SizeOf<T>(), d06.AsByte());
            Store((byte *) ptr + 06*N*Unsafe.SizeOf<T>(), d07.AsByte());
            Store((byte *) ptr + 07*N*Unsafe.SizeOf<T>(), d08.AsByte());
            Store((byte *) ptr + 08*N*Unsafe.SizeOf<T>(), d09.AsByte());
            Store((byte *) ptr + 09*N*Unsafe.SizeOf<T>(), d10.AsByte());
            Store((byte *) ptr + 10*N*Unsafe.SizeOf<T>(), d11.AsByte());
            Store((byte *) ptr + 11*N*Unsafe.SizeOf<T>(), d12.AsByte());
            Store((byte *) ptr + 12*N*Unsafe.SizeOf<T>(), d13.AsByte());
            Store((byte *) ptr + 13*N*Unsafe.SizeOf<T>(), d14.AsByte());
        }
        [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort15V(T* ptr)
        {
            var N = Vector256<T>.Count;

            var d01 = LoadDquVector256((byte *) ptr + 00*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d02 = LoadDquVector256((byte *) ptr + 01*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d03 = LoadDquVector256((byte *) ptr + 02*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d04 = LoadDquVector256((byte *) ptr + 03*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d05 = LoadDquVector256((byte *) ptr + 04*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d06 = LoadDquVector256((byte *) ptr + 05*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d07 = LoadDquVector256((byte *) ptr + 06*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d08 = LoadDquVector256((byte *) ptr + 07*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d09 = LoadDquVector256((byte *) ptr + 08*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d10 = LoadDquVector256((byte *) ptr + 09*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d11 = LoadDquVector256((byte *) ptr + 10*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d12 = LoadDquVector256((byte *) ptr + 11*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d13 = LoadDquVector256((byte *) ptr + 12*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d14 = LoadDquVector256((byte *) ptr + 13*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d15 = LoadDquVector256((byte *) ptr + 14*N*Unsafe.SizeOf<T>()).As<byte, T>();

            BitonicSort15VGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08, ref d09, ref d10, ref d11, ref d12, ref d13, ref d14, ref d15);

            Store((byte *) ptr + 00*N*Unsafe.SizeOf<T>(), d01.AsByte());
            Store((byte *) ptr + 01*N*Unsafe.SizeOf<T>(), d02.AsByte());
            Store((byte *) ptr + 02*N*Unsafe.SizeOf<T>(), d03.AsByte());
            Store((byte *) ptr + 03*N*Unsafe.SizeOf<T>(), d04.AsByte());
            Store((byte *) ptr + 04*N*Unsafe.SizeOf<T>(), d05.AsByte());
            Store((byte *) ptr + 05*N*Unsafe.SizeOf<T>(), d06.AsByte());
            Store((byte *) ptr + 06*N*Unsafe.SizeOf<T>(), d07.AsByte());
            Store((byte *) ptr + 07*N*Unsafe.SizeOf<T>(), d08.AsByte());
            Store((byte *) ptr + 08*N*Unsafe.SizeOf<T>(), d09.AsByte());
            Store((byte *) ptr + 09*N*Unsafe.SizeOf<T>(), d10.AsByte());
            Store((byte *) ptr + 10*N*Unsafe.SizeOf<T>(), d11.AsByte());
            Store((byte *) ptr + 11*N*Unsafe.SizeOf<T>(), d12.AsByte());
            Store((byte *) ptr + 12*N*Unsafe.SizeOf<T>(), d13.AsByte());
            Store((byte *) ptr + 13*N*Unsafe.SizeOf<T>(), d14.AsByte());
            Store((byte *) ptr + 14*N*Unsafe.SizeOf<T>(), d15.AsByte());
        }
        [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.AggressiveOptimization)]
        static void BitonicSort16V(T* ptr)
        {
            var N = Vector256<T>.Count;

            var d01 = LoadDquVector256((byte *) ptr + 00*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d02 = LoadDquVector256((byte *) ptr + 01*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d03 = LoadDquVector256((byte *) ptr + 02*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d04 = LoadDquVector256((byte *) ptr + 03*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d05 = LoadDquVector256((byte *) ptr + 04*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d06 = LoadDquVector256((byte *) ptr + 05*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d07 = LoadDquVector256((byte *) ptr + 06*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d08 = LoadDquVector256((byte *) ptr + 07*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d09 = LoadDquVector256((byte *) ptr + 08*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d10 = LoadDquVector256((byte *) ptr + 09*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d11 = LoadDquVector256((byte *) ptr + 10*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d12 = LoadDquVector256((byte *) ptr + 11*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d13 = LoadDquVector256((byte *) ptr + 12*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d14 = LoadDquVector256((byte *) ptr + 13*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d15 = LoadDquVector256((byte *) ptr + 14*N*Unsafe.SizeOf<T>()).As<byte, T>();
            var d16 = LoadDquVector256((byte *) ptr + 15*N*Unsafe.SizeOf<T>()).As<byte, T>();

            BitonicSort16VGeneric(ref d01, ref d02, ref d03, ref d04, ref d05, ref d06, ref d07, ref d08, ref d09, ref d10, ref d11, ref d12, ref d13, ref d14, ref d15, ref d16);

            Store((byte *) ptr + 00*N*Unsafe.SizeOf<T>(), d01.AsByte());
            Store((byte *) ptr + 01*N*Unsafe.SizeOf<T>(), d02.AsByte());
            Store((byte *) ptr + 02*N*Unsafe.SizeOf<T>(), d03.AsByte());
            Store((byte *) ptr + 03*N*Unsafe.SizeOf<T>(), d04.AsByte());
            Store((byte *) ptr + 04*N*Unsafe.SizeOf<T>(), d05.AsByte());
            Store((byte *) ptr + 05*N*Unsafe.SizeOf<T>(), d06.AsByte());
            Store((byte *) ptr + 06*N*Unsafe.SizeOf<T>(), d07.AsByte());
            Store((byte *) ptr + 07*N*Unsafe.SizeOf<T>(), d08.AsByte());
            Store((byte *) ptr + 08*N*Unsafe.SizeOf<T>(), d09.AsByte());
            Store((byte *) ptr + 09*N*Unsafe.SizeOf<T>(), d10.AsByte());
            Store((byte *) ptr + 10*N*Unsafe.SizeOf<T>(), d11.AsByte());
            Store((byte *) ptr + 11*N*Unsafe.SizeOf<T>(), d12.AsByte());
            Store((byte *) ptr + 12*N*Unsafe.SizeOf<T>(), d13.AsByte());
            Store((byte *) ptr + 13*N*Unsafe.SizeOf<T>(), d14.AsByte());
            Store((byte *) ptr + 14*N*Unsafe.SizeOf<T>(), d15.AsByte());
            Store((byte *) ptr + 15*N*Unsafe.SizeOf<T>(), d16.AsByte());
        }

        public const int MinBitonicSortSize = 8;
        public const int MaxBitonicSortSize = 128;

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static void Sort(T* ptr, int length)
        {
            var N = Vector256<T>.Count;
            Debug.Assert(length % N == 0);
            Debug.Assert(length <= MaxBitonicSortSize);

            switch (length / N) {
                case 01: BitonicSort01V(ptr); return;
                case 02: BitonicSort02V(ptr); return;
                case 03: BitonicSort03V(ptr); return;
                case 04: BitonicSort04V(ptr); return;
                case 05: BitonicSort05V(ptr); return;
                case 06: BitonicSort06V(ptr); return;
                case 07: BitonicSort07V(ptr); return;
                case 08: BitonicSort08V(ptr); return;
                case 09: BitonicSort09V(ptr); return;
                case 10: BitonicSort10V(ptr); return;
                case 11: BitonicSort11V(ptr); return;
                case 12: BitonicSort12V(ptr); return;
                case 13: BitonicSort13V(ptr); return;
                case 14: BitonicSort14V(ptr); return;
                case 15: BitonicSort15V(ptr); return;
                case 16: BitonicSort16V(ptr); return;

                default:
                    throw new NotSupportedException("length is not power a multiple of 8 && <= 128");
            }
        }
    }
}
